In [2]:
from math import floor
import numpy as np
import pandas as pd

In [3]:
cols = ['arch',
        'F1_NONE', 'F1_F1', 'F1_F2', 'F1_F3', 'F1_F4',
        'F2_NONE', 'F2_F1', 'F2_F2', 'F2_F3', 'F2_F4',
        'F3_NONE', 'F3_F1', 'F3_F2', 'F3_F3', 'F3_F4',
        'F4_NONE', 'F4_F1', 'F4_F2', 'F4_F3', 'F4_F4',
        'N1_NONE', 'N1_F1', 'N1_F2', 'N1_F3', 'N1_F4',
        'N2_NONE', 'N2_F1', 'N2_F2', 'N2_F3', 'N2_F4',

        'RET_F1_NONE', 'RET_F1_F1', 'RET_F1_F2', 'RET_F1_F3', 'RET_F1_F4',
        'RET_F2_NONE', 'RET_F2_F1', 'RET_F2_F2', 'RET_F2_F3', 'RET_F2_F4',
        'RET_F3_NONE', 'RET_F3_F1', 'RET_F3_F2', 'RET_F3_F3', 'RET_F3_F4',
        'RET_F4_NONE', 'RET_F4_F1', 'RET_F4_F2', 'RET_F4_F3', 'RET_F4_F4',
        'RET_N1_NONE', 'RET_N1_F1', 'RET_N1_F2', 'RET_N1_F3', 'RET_N1_F4',
        'RET_N2_NONE', 'RET_N2_F1', 'RET_N2_F2', 'RET_N2_F3', 'RET_N2_F4',

        'RET2_F1_NONE', 'RET2_F1_F1', 'RET2_F1_F2', 'RET2_F1_F3', 'RET2_F1_F4',
        'RET2_F2_NONE', 'RET2_F2_F1', 'RET2_F2_F2', 'RET2_F2_F3', 'RET2_F2_F4',
        'RET2_F3_NONE', 'RET2_F3_F1', 'RET2_F3_F2', 'RET2_F3_F3', 'RET2_F3_F4',
        'RET2_F4_NONE', 'RET2_F4_F1', 'RET2_F4_F2', 'RET2_F4_F3', 'RET2_F4_F4',
        'RET2_N1_NONE', 'RET2_N1_F1', 'RET2_N1_F2', 'RET2_N1_F3', 'RET2_N1_F4',
        'RET2_N2_NONE', 'RET2_N2_F1', 'RET2_N2_F2', 'RET2_N2_F3', 'RET2_N2_F4']

columns = {x:k for k,x in enumerate(cols)}

numbered_columns = cols[1:]

In [5]:
'''
NOTE THAT THE "NORMAL 2" PATTERN COULD BE OUT OF PATTERN. REQUIRED 2 LINES as 2x2 array. IF THIS HAPPENED, MUST BE MANUALLY CONVERTED TO THE REQUIRED PATTERN AS BELOW!

REQUIRED
[[1. 0.]
 [0. 0.]]

OUT OF PATTERN
[[1.]]
'''

with open('./outputs/output_samknn_skflow_dr_2-ts_0.8-lf_1-limit_500-wl_1_temp.txt') as f:
    lines = f.readlines()

height = 91
times = floor(len(lines)/height)

output = pd.DataFrame(np.zeros((times, len(columns))), columns=columns)

for k, column_name in enumerate(columns):
    column_init_position = columns[column_name]

    for time in np.arange(0, times):
        line_number = column_init_position+(time*height)
        value = lines[line_number].rstrip("\n")

        if (column_name in numbered_columns):
            value = float(value)

        output.iloc[time,k] = value

f.close()

In [7]:
q1 = output.query('F1_F1 > 50 and F2_F2 > 50 and RET_F1_F1 > 50 and RET_F2_F2 > 50 and RET_F3_F3 > 50 and RET2_F1_F1 > 50 and RET2_F2_F2 > 50 and RET2_F3_F3 > 50 and RET2_F4_F4 > 50')

In [8]:
q1

,arch,F1_NONE,F1_F1,F1_F2,F1_F3,F1_F4,F2_NONE,F2_F1,F2_F2,F2_F3,...,RET2_N1_NONE,RET2_N1_F1,RET2_N1_F2,RET2_N1_F3,RET2_N1_F4,RET2_N2_NONE,RET2_N2_F1,RET2_N2_F2,RET2_N2_F3,RET2_N2_F4
1,SAMKNN 5000 2 2 2 distance maxACC 10000 800 1000,1.250,98.750,0.0,0.0,0.0,1.125,0.125,98.750,0.0,...,11.000,78.500,0.0,10.500,0.000,9.875,89.625,0.0,0.500,0.00
2,SAMKNN 5000 5 2 2 distance maxACC 10000 800 1000,1.000,99.000,0.0,0.0,0.0,0.375,0.125,99.500,0.0,...,3.750,81.625,0.0,14.625,0.000,2.250,93.125,0.0,4.625,0.00
3,SAMKNN 5000 10 2 2 distance maxACC 10000 800 1000,1.000,99.000,0.0,0.0,0.0,0.375,0.125,99.500,0.0,...,3.500,81.500,0.0,15.000,0.000,1.500,93.375,0.0,5.125,0.00
4,SAMKNN 5000 20 2 2 distance maxACC 10000 800 1000,0.375,99.625,0.0,0.0,0.0,0.375,0.125,99.500,0.0,...,3.375,81.625,0.0,15.000,0.000,1.125,93.500,0.0,5.375,0.00
11,SAMKNN 5000 2 2 2 distance maxACCApprox 10000 ...,1.125,98.875,0.0,0.0,0.0,1.125,0.125,98.750,0.0,...,10.875,78.500,0.0,10.625,0.000,9.750,89.625,0.0,0.625,0.00
12,SAMKNN 5000 5 2 2 distance maxACCApprox 10000 ...,0.875,99.125,0.0,0.0,0.0,0.500,0.125,99.375,0.0,...,3.500,81.375,0.0,15.125,0.000,2.000,93.125,0.0,4.875,0.00
13,SAMKNN 5000 10 2 2 distance maxACCApprox 10000...,0.875,99.125,0.0,0.0,0.0,0.500,0.125,99.375,0.0,...,3.250,81.625,0.0,15.125,0.000,1.250,93.375,0.0,5.375,0.00
14,SAMKNN 5000 20 2 2 distance maxACCApprox 10000...,0.375,99.625,0.0,0.0,0.0,0.500,0.125,99.375,0.0,...,3.000,81.625,0.0,15.375,0.000,0.750,93.500,0.0,5.750,0.00
40,SAMKNN 5000 1 2 5 distance maxACC 10000 800 1000,2.250,97.750,0.0,0.0,0.0,2.125,0.125,97.750,0.0,...,0.000,72.500,0.0,7.125,20.375,0.000,78.125,0.0,0.125,21.75
41,SAMKNN 5000 2 2 5 distance maxACC 10000 800 1000,1.875,98.125,0.0,0.0,0.0,1.750,0.125,98.125,0.0,...,11.625,77.750,0.0,10.625,0.000,9.875,89.625,0.0,0.500,0.00
42,SAMKNN 5000 5 2 5 distance maxACC 10000 800 1000,1.750,98.250,0.0,0.0,0.0,1.125,0.125,98.750,0.0,...,5.625,79.500,0.0,14.875,0.000,2.500,93.125,0.0,4.375,0.00
43,SAMKNN 5000 10 2 5 distance maxACC 10000 800 1000,1.625,98.375,0.0,0.0,0.0,1.000,0.125,98.875,0.0,...,5.500,79.250,0.0,15.250,0.000,2.000,93.250,0.0,4.750,0.00
44,SAMKNN 5000 20 2 5 distance maxACC 10000 800 1000,1.000,99.000,0.0,0.0,0.0,0.875,0.125,99.000,0.0,...,4.875,79.250,0.0,15.875,0.000,1.875,93.250,0.0,4.875,0.00
46,SAMKNN 5000 2 5 5 distance maxACC 10000 800 1000,2.500,97.500,0.0,0.0,0.0,2.500,0.000,97.500,0.0,...,11.875,86.875,0.0,1.250,0.000,10.375,89.250,0.0,0.375,0.00
47,SAMKNN 5000 5 5 5 distance maxACC 10000 800 1000,2.125,97.875,0.0,0.0,0.0,2.250,0.000,97.750,0.0,...,6.250,88.750,0.0,5.000,0.000,3.125,93.125,0.0,3.750,0.00